version: "3.8"
services:
  app:
    container_name: web
    hostname: nextjsserver
    build: .
    restart: always
    command: bash -c 'while !</dev/tcp/db/3306; do sleep 1; done; npm run start'
    ports:
      - "9000:4000"
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: mysql:8.0.25
    container_name: db
    hostname: db
    volumes:
      - db_data:/var/lib/mysql
      - db_config:/etc/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "Ubuntu@pa$$wOr1d"
      MYSQL_DATABASE: "database_development"
      MYSQL_PASSWORD: "Ubuntu@pa$$wOr1d"
      MYSQL_USER: "jimmy"
    ports:
      - "3306:3306"
        

volumes:
  db_data:
  db_config:
